site_name: Troop 61 Library Documentation

repo_name: troop61killbuck/Troop61LibraryDocs
repo_url: https://github.com/troop61killbuck/Troop61LibraryDocs
edit_uri: ""

site_description: Troop 61 Library Documentation
site_author: Jack Veney - Troop 61
theme:
  name: material
  custom_dir: material
  features:
    - navigation.tabs
  logo: assets/Troop61.png
  favicon: assets/Troop61.png
  icon:
    repo: fontawesome/brands/github
  language: en

copyright: Copyright &copy; 2020 BSA Troop 4061 - Wooster, Ohio
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
  - git-revision-date-localized:
      fallback_to_build_date: true 

# Page tree
#nav:
#  - Home: index.md
#  - Catalog:
#    - Librarika: Catalog/index.md
#  - Administration:
#    - 'Home': 'Administration/index.md'
#    - 'User Guide': 
#      - 'Getting Started': 'Administration/getting-started.md'
#      - 'OPAC': 'Administration/opacs.md'
#      - 'Library': 'Administration/libraries.md'
#      - 'Cataloging (Books)': 'Administration/cataloging.md'
#      - 'Members (Patrons)': 'Administration/members.md'
#      - 'Circulations (Loans)': 'Administration/circulations.md'
#      - 'Fees & Payments': 'Administration/fees-payments.md'
#      - 'Barcode Labels': 'Administration/barcode-labels.md'
#      - 'Reports': 'Administration/reports.md'
#      - 'Member Area': 'Administration/member-area.md'
#      - 'Users': 'Administration/users.md'
#      - 'Bulk Actions': 'Administration/bulk-actions.md'
#    - 'Contributing': 'Administration/contribute.md'
#    - 'About': 'Administration/about.md'
#    - 'License': 'Administration/license.md'
