site_name: Troop 61 Library Documentation
repo_url: https://github.com/jackveney/Troop61LibraryDocs
repo_name: GitHub
site_description: Troop 61 Library Documentation
site_author: Jack Veney - Troop 61
theme: readthedocs
nav:
    - 'Home': 'index.md'
    - 'User Guide': 
      - 'Getting Started': 'getting-started.md'
      - 'OPAC': 'opacs.md'
      - 'Library': 'libraries.md'
      - 'Cataloging (Books)': 'cataloging.md'
      - 'Members (Patrons)': 'members.md'
      - 'Circulations (Loans)': 'circulations.md'
      - 'Fees & Payments': 'fees-payments.md'
      - 'Barcode Labels': 'barcode-labels.md'
      - 'Reports': 'reports.md'
      - 'Member Area': 'member-area.md'
      - 'Users': 'users.md'
      - 'Bulk Actions': 'bulk-actions.md'
    - 'Contributing': 'contribute.md'
    - 'About': 'about.md'
    - 'License': 'license.md'
